#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Set the path to custom_components
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Activate the virtual environment
source "${PWD}/.venv/bin/activate"

ruff format .
ruff check . --fix