#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create a virtual environment
python3 -m venv .venv
# Activate the virtual environment
source "${PWD}/.venv/bin/activate"

# Make the scripts executable
sudo chmod -R +x ${PWD}/scripts

# Install the required packages
python3 -m pip install --upgrade pip
python3 -m pip install --requirement requirements.txt

# Output the Python interpreter path to a file
echo "/workspaces/$(basename $PWD)/.venv/bin/python" > /workspaces/$(basename $PWD)/.venv/.env